### ISSUE TITLE
Unclear error directive about __rental_structs_and_impls

### ISSUE THREAD

**Issue by spease** [jpernst/rental#23]
```
error[E0596]: cannot borrow immutable borrowed content `*ctx.enumerator` as mutable
   --> src/main.rs:194:21
    |
143 | / rental! {
144 | |   pub mod rent_manager {
145 | |     use libudev;
146 | |
...   |
153 | |   }
154 | | }
    | |_- use `&__rental_structs_and_impls mut __rental_structs_and_impls` here to make mutable
...
194 |         for device in ctx.enumerator.scan_devices()? {
    |                       ^^^^^^^^^^^^^^ cannot borrow as mutable
    |
    = note: this error originates in a macro outside of the current crate
```

I'm not sure what this error is directing me to do. I just want to access the middle field of a three-item struct. I also need to access the last item in another function, so I can't simply re-order the struct.

Just wanted to say thanks for making this crate since this is my third ticket today. I'm really disappointed that Rust still hasn't fixed self-referential structs, it seems to be a common problem and has cost me hours today. So this crate has been my only way of using inherently self-referential APIs.

**Comment by jpernst** [comment]
Without more context I can't really guess what's going on here; I'd need to see at least the full rental invocation.

**Comment by spease** [comment]
The struct:
```
rental! {
  pub mod rent_manager {
    use libudev;

    #[rental]
    pub struct Manager {
      context: Box<libudev::Context>,
      enumerator: Box<libudev::Enumerator<'context>>,
      monitor_socket: libudev::MonitorSocket<'context>,
    }
  }
}
```

The invocation:
```
  pub fn start(&mut self, i_ws: &mut WpaSupplicant) -> Result<()> {
    self.rent_all_mut(|ctx|{
      for device in ctx.enumerator.scan_devices()? {
        match Self::device_add(&device, i_ws) {
          Err(e) => error!("\"{:?}\"", e),
          _ => {},
        }
      }
      Ok(())
    })
  }
```

**Comment by jpernst** [comment]
Ok, I think I see the problem. In rental structs, there's an implied dependency on each field by the subsequent fields. It prevents you from mutating `enumerator` because there are later fields which might be holding a ref to it. However, based on the lifetime relationship on display here, `enumerator` and `monitor_socket` have no dependency on eachother. I suggest creating another struct that can hold both of those, then using that struct as the second field in your rental struct. This will make `enumerator` and `monitor_socket` peers instead of implying a dependency. You can then use `rent_mut` to get mutable access to both.

It might be possible to fix this in rental by doing a dependency analysis of the lifetimes to determine what can possibly reference what, but that's non-trivial. For now, just stuffing unrelated fields in another struct will solve your problem.

**Comment by spease** [comment]
Thanks, I'll try that.

I suppose it would be possible by doing dependency analysis, but I agree with the rust-lang.org thread that self-referential structs should be part of the language. I don't have a whole lot of time to spend on side projects, but if I can do anything to help, please let me know.

Past that, my only feedback here is that a better error message would be nice if someone tries to access a middle variable, but if that's non-trivial too, feel free to close this.
