### ISSUE TITLE
Cannot infer appropriate lifetime error when using rent_all

### ISSUE THREAD

**Issue by typon** [jpernst/rental#29]
Hi there,

I've isolated my code, here's the snippet that reproduces the issue:

```rust
#[macro_use]
extern crate rental;

rental! {
    mod rentals {
        use super::*;
        #[rental(debug)]
        pub struct Wrapper {
            string: String,
            obj: TakesRef<'string>,
        }
    }
}

#[derive(Debug)]
pub struct TakesRef<'a> {
    pub string_ref: &'a str
}
impl<'a> TakesRef<'a> {
    fn new(string_ref: &'a str) -> TakesRef<'a> {
        TakesRef {string_ref}    
    }
}

fn main () {
    let wr = rentals::Wrapper::new("hello".to_string(), |string| TakesRef::new(&string));
    let inner_obj = wr.rent_all(|b| b.obj); // Error here: cannot infer an appropriate lifetime due to conflicting requirements
}

```

How can I access in the internals of the wrapper rental object? I'm trying to follow the example in your test code.

**Comment by jpernst** [comment]
It's unsafe to arbitrarily borrow inner parts of a rental struct, so rental doesn't allow that in the general case. You have a couple choices: You can do all the work you need to do inside the closure, instead of returning the obj, or you can try the `covariant` feature. Your `TakeRef` struct uses a shared reference, so it should satisfy the requirements for the `covariant` option. This will allow you do access  `obj` directly since it's safe to do so under those conditions.

**Comment by typon** [comment]
I tried covariant, it was as simple as updating the attribute.

Here's the updated code for future readers:

```rust
#[macro_use]
extern crate rental;

rental! {
    mod rentals {
        use super::*;
        #[rental(covariant)]
        pub struct Wrapper {
            string: String,
            obj: TakesRef<'string>,
        }
    }
}

#[derive(Debug)]
pub struct TakesRef<'a> {
    pub string_ref: &'a str
}
impl<'a> TakesRef<'a> {
    fn new(string_ref: &'a str) -> TakesRef<'a> {
        TakesRef {string_ref}    
    }
}

fn main () {
    let wr = rentals::Wrapper::new("hello".to_string(), |string| TakesRef::new(&string));
    let inner_obj = wr.all().obj;
    println!("inner_obj: {:?}", inner_obj);
}
```
And everything works as I expected. Thanks a lot dude/dudette!
