### ISSUE TITLE
How to combine, Arc, RwLock and referencing result

### ISSUE THREAD

**Issue by dignifiedquire** [jpernst/rental#37]
I am trying to make the following code work

```rust
rental! {
    pub mod rentals {
        use super::*;

        #[rental]
        pub struct ChatlistWrapper {
            lock: std::sync::Arc<std::sync::RwLock<Option<Context>>>,
            guard: std::sync::RwLockReadGuard<'lock, Option<Context>>,
            list: Chatlist<'guard>,
        }
    }
}

pub struct Context {}

pub struct Chatlist<'a> {
  context: &'a Context,
}
```

But am running into the following issue

```
help: message: Struct `ChatlistWrapper` field `guard` must be a type path with 1 type param, `String`, or a reference.
```

Any tips on how to make this work?

**Comment by ufoscout** [comment]
@dignifiedquire 
did you find a solution? I am facing the same problem

**Comment by dignifiedquire** [comment]
no :(

**Comment by jpernst** [comment]
Sorry for missing this issue for so long. The problem here is the syntax hack I had to use to work around bugs in the compiler. Rental attempts to deduce the deref type of a field by looking between the angle brackets and assuming what's there is the deref target. It gets confused if there are multiple args.

This can be worked around with the `target_ty` field attribute, like so:

```rust
		#[rental]
		pub struct ArcBugStruct {
			head: std::sync::Arc<std::sync::RwLock<Option<i32>>>,
			#[target_ty = "Option<i32>"]
			guard: std::sync::RwLockReadGuard<'head, Option<i32>>,
			foo: &'guard i32,
		}
```

Here, `target_ty` tells rental that the guard field will deref to `Option<i32>`. If you get the type wrong, the struct will fail to compile, so there's no danger of unsoundness, but it's still an unfortunate necessity. It's possible the situation has changed since I wrote this and perhaps the compiler bugs no longer exist, but I don't really use rust anymore so likely won't be revisiting this.
