### ISSUE TITLE
troubles with Capn Proto

### ISSUE THREAD

**Issue by MarkSwanson** [jpernst/rental#9]
Hello,

I'm investigating your nice library but got stuck on the first thing I tried:

```
rental! {
    pub mod rent_point {
        use test::point_capnp::{point};

        #[rental(deref_suffix)]
        pub struct RentPoint {
            v: Vec<u8>,
            point2: point::Reader<'v>,
        }
    }
}
```
The error is:
```
the trait `std::ops::Deref` is not implemented for `test::point_capnp::point::Reader<'static>`
```
This doesn't make sense to me because in your 'alto' example your 'struct Alto' isn't a stable deref target. I trust rental is doing the right thing, but why doesn't 'struct Alto' need to be StableDeref?

So if I use Box to create a StableDeref I get further:
```
point2: Box<point::Reader<'v>>,
```

Error chain:
cannot infer an appropriate lifetime due to conflicting requirements

first, the lifetime cannot outlive the lifetime 'v
  (I wish rust specified what the lifetime was instead of just saying, 'the lifetime')

...so that expression is assignable (expected &'point2 test::point_capnp::point::Reader<'_>, found &'point2 test::point_capnp::point::Reader<'v>)
  (It is assignable. the '_ lifetime means "I don't care" so I don't understand why this isn't assignable! ??)

but, the lifetime must be valid for the anonymous lifetime #1 defined on the body at 12:32...
  (arg, none of the line numbers are useful - they all point to the start of the macro)
  (I am guessing the anonymous lifetime refers to the start of some internal function as generated by the macro?)

...so that the type `test::point_capnp::point::Reader<'_>` is not borrowed for too long

Fyi 'Reader' is:
```
#[derive(Clone, Copy)]
  pub struct Reader<'a> { reader: layout::StructReader<'a> }
```

Note: I can get this to compile by changing to this:
```
point2: Box<point::Reader<'static>>,
```

I would expect this to blow up though :-) Because if the Vec is dropped first and someone uses point2 we have UB/segfault/badness.

Any thoughts or suggestions would be much appreciated!

**Comment by jpernst** [comment]
The reason you're getting that error is the `deref_suffix` option in in the rental attribute. That means rental will try to impl `Deref` for the rental struct itself by forwarding it to the `Deref` impl of the suffix field. I don't know what `Reader` is exactly, but if it doesn't have a `Deref` impl, then remove the `deref_suffix` option and that should fix the first problem.

Putting reader in a `Box` as you've done will give it a `Deref` impl, but the `Target` type of that impl contains the special `'v` lifetime created by rental. Exposing this lifetime to the outside world would be very unsafe, which is why I've made sure such situations won't compile. This is what the "conflicting requirements" error is about.

By changing the lifetime to `'static` as you've done in the last example, you've removed the special rental lifetime, so now it's an acceptable deref. However, you won't actually be able to successfully instantiate this rental struct, since the closure will take a vec bounded by `'v` and expect a `Reader<'static>` to be returned, which can't be done. If this were allowed, you're right that it would result in potential memory errors.

So, to sum all of this up, removing the `deref_suffix` option should get you back on the right track. Let me know if that works or if you have any other problems.

**Comment by MarkSwanson** [comment]
Excellent response -thanks a bunch! 

I just found the Macro rental::rental docs - these seem excellent and I'm not sure why I didn't think to click on them in the first place. It might(?) be worth it to explicitly point people to your nice "Macro rental" docs in the examples.

I'm compiling fine!
Thanks again!
